config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root  to: 'ajax_test#top'
  root "welcome#index"
  post  'ajax_test/update', to: 'ajax_test#update', as: 'ajax_test_update'
  get "home", to: "home#index", as: "user_root"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  def self.find_for_facebook_oauth(auth)
    user = User.where(provider: auth.provider, uid: auth.uid).first

    unless user
      user = User.create( name:     auth.extra.raw_info.name,
                          provider: auth.provider,
                          uid:      auth.uid,
                          email:    auth.info.email,
                          token:    auth.credentials.token,
                          password: Devise.friendly_token[0,20] )
    end

    return user
  end
end

app/controllers/ajax_test_controller.rb
class AjaxTestController < ApplicationController
  def top

  end

  def update
    post_text = params[:data][:text]
    results = { :message => post_text }
    render partial: 'ajax_partial', locals: { :results => results }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def authenticate_user!
    session[:user_return_to] = Rails.env['PATH_INFO']
    redirect_to user_omniauth_authorize_path(:facebook) unless user_signed_in?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    #raise request.env['omniauth.auth'].to_yaml
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/ajax_test_helper.rb
module AjaxTestHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ajax_test/_ajax_partial.html.erb
Callback Msg = <%= results[:message] %>

app/views/ajax_test/top.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<div id="request_ajax_update" >
  <%= form_tag(ajax_test_update_path, method: :post, remote: true) { %>
      <%= text_field :data, :text %>
      <%= submit_tag 'Post AJAX' %>
  <% } %>
</div>

<hr>
<div id="updated_by_ajax" >
  DEFAULT
</div>
<hr>
</body>
</html>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AjaxTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <div id="user-info">
    <% if user_signed_in? %>
      <%= current_user.name %>
      [<%= link_to 'Sign out', destroy_user_session_path, method: :delete  %>]
    <% else %>
      <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
    <% end %>
  </div>
  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>